version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: next-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nextdb
      POSTGRES_USER: nextuser
      POSTGRES_PASSWORD: nextpass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
